version: '3'
services:

  amd64:
    build:
      context: .
      args:
        ARCH: amd64
    command: >
      sh -c "cmake -S ./src -B ./build-amd64 &&
             cmake --build ./build-amd64 &&
            ./build-amd64/Tutorial 4294967296"
    volumes:
      - .:/app

  arm32v5:
    build:
      context: .
      args:
        ARCH: arm32v5
    command: >
      sh -c "cmake -S ./src -B ./build-arm32v5 &&
             cmake --build ./build-arm32v5 &&
            ./build-arm32v5/Tutorial 4294967296"
    volumes:
      - .:/app

  arm32v7:
    build:
      context: .
      args:
        ARCH: arm32v7
    command: >
      sh -c "cmake -S ./src -B ./build-arm32v7 &&
             cmake --build ./build-arm32v7 &&
            ./build-arm32v7/Tutorial 4294967296"
    volumes:
      - .:/app

  arm64v8:
    build:
      context: .
      args:
        ARCH: arm64v8
    command: >
      sh -c "cmake -S ./src -B ./build-arm64v8 &&
             cmake --build ./build-arm64v8 &&
            ./build-arm64v8/Tutorial 4294967296"
    volumes:
      - .:/app

  i386:
    build:
      context: .
      args:
        ARCH: i386
    command: >
      sh -c "cmake -S ./src -B ./build-i386 &&
             cmake --build ./build-i386 &&
            ./build-i386/Tutorial 4294967296"
    volumes:
      - .:/app

  mips64le:
    build:
      context: .
      args:
        ARCH: mips64le
    command: >
      sh -c "cmake -S ./src -B ./build-mips64le &&
             cmake --build ./build-mips64le &&
            ./build-mips64le/Tutorial 4294967296"
    volumes:
      - .:/app

  ppc64le:
    build:
      context: .
      args:
        ARCH: ppc64le
    command: >
      sh -c "cmake -S ./src -B ./build-ppc64le &&
             cmake --build ./build-ppc64le &&
            ./build-ppc64le/Tutorial 4294967296"
    volumes:
      - .:/app

  riscv64:
    build:
      context: .
      args:
        ARCH: riscv64
        TAG: sid-slim
    command: >
      sh -c "cmake -S ./src -B ./build-riscv64 &&
             cmake --build ./build-riscv64 &&
            ./build-riscv64/Tutorial 4294967296"
    volumes:
      - .:/app

  s390x:
    build:
      context: .
      args:
        ARCH: s390x
    command: >
      sh -c "cmake -S ./src -B ./build-s390x &&
             cmake --build ./build-s390x &&
            ./build-s390x/Tutorial 4294967296"
    volumes:
      - .:/app
