version: '3'
services:

  linux:
    build:
      context: .
    environment:
      CROSS_TRIPLE: x86_64-linux-gnu
      FOLDER: linux
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  mac:
    build:
      context: .
    environment:
      CROSS_TRIPLE: x86_64-apple-darwin
      FOLDER: mac
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  win:
    build:
      context: .
    environment:
      CROSS_TRIPLE: x86_64-w64-mingw32
      FOLDER: win
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build
