version: '3'
services:

  linux:
    image: kmturley/crossbuild
    environment:
      CROSS_TRIPLE: x86_64-linux-gnu
    working_dir: /app
    command: >
      sh -c "cmake -DUSE_MYMATH=0 -S ./src -B ./build/linux &&
             cmake --build ./build/linux &&
            file ./build/linux/Tutorial"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  mac:
    image: kmturley/crossbuild
    environment:
      CROSS_TRIPLE: x86_64-apple-darwin
    working_dir: /app
    command: >
      sh -c "cmake -DUSE_MYMATH=0 -S ./src -B ./build/mac &&
             cmake --build ./build/mac &&
            file ./build/mac/Tutorial"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  win:
    image: kmturley/crossbuild
    environment:
      CROSS_TRIPLE: x86_64-w64-mingw32
    working_dir: /app
    command: >
      sh -c "cmake -DUSE_MYMATH=0 -S ./src -B ./build/win &&
             cmake --build ./build/win &&
            file ./build/win/Tutorial.exe"
    volumes:
      - ./src:/app/src
      - ./build:/app/build
