version: '3'
services:

  linux-amd64:
    build:
      context: .
      args:
        ARCH: amd64
    environment:
      FOLDER: linux-amd64
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  linux-arm32v5:
    build:
      context: .
      args:
        ARCH: arm32v5
    environment:
      FOLDER: linux-arm32v5
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  linux-arm32v7:
    build:
      context: .
      args:
        ARCH: arm32v7
    environment:
      FOLDER: linux-arm32v7
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  linux-arm64v8:
    build:
      context: .
      args:
        ARCH: arm64v8
    environment:
      FOLDER: linux-arm64v8
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  linux-i386:
    build:
      context: .
      args:
        ARCH: i386
    environment:
      FOLDER: linux-i386
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  linux-mips64le:
    build:
      context: .
      args:
        ARCH: mips64le
    environment:
      FOLDER: linux-mips64le
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  linux-ppc64le:
    build:
      context: .
      args:
        ARCH: ppc64le
    environment:
      FOLDER: linux-ppc64le
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  linux-riscv64:
    build:
      context: .
      args:
        ARCH: riscv64
        OS: debian:sid-slim
    environment:
      FOLDER: linux-riscv64
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  linux-s390x:
    build:
      context: .
      args:
        ARCH: s390x
    environment:
      FOLDER: linux-s390x
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build
