version: '3'
services:

  linux:
    build:
      context: .
      args:
        OS: linux-x64
    environment:
      FOLDER: linux
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  # mac:
  #   build:
  #     context: .
  #     args:
  #       OS: mac-x64
  #   environment:
  #     FOLDER: mac
  #   command: >
  #     sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
  #            cmake --build ./build/$${FOLDER} &&
  #           ./build/$${FOLDER}/Tutorial 4294967296"
  #   volumes:
  #     - ./src:/app/src
  #     - ./build:/app/build

  win:
    build:
      context: .
      args:
        OS: windows-shared-x64
    environment:
      FOLDER: win
    command: >
      sh -c "cmake -S ./src -B ./build/$${FOLDER} &&
             cmake --build ./build/$${FOLDER} &&
            ./build/$${FOLDER}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build
