version: '3'
services:

  x86_64-linux-gnu:
    build:
      context: .
    environment:
      CROSS_TRIPLE: x86_64-linux-gnu
    command: >
      sh -c "cmake -S ./src -B ./build/$${CROSS_TRIPLE} &&
             cmake --build ./build/$${CROSS_TRIPLE} &&
            ./build/$${CROSS_TRIPLE}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  x86_64-apple-darwin:
    build:
      context: .
    environment:
      CROSS_TRIPLE: x86_64-apple-darwin
    command: >
      sh -c "cmake -S ./src -B ./build/$${CROSS_TRIPLE} &&
             cmake --build ./build/$${CROSS_TRIPLE} &&
            ./build/$${CROSS_TRIPLE}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build

  x86_64-w64-mingw32:
    build:
      context: .
    environment:
      CROSS_TRIPLE: x86_64-w64-mingw32
    command: >
      sh -c "cmake -S ./src -B ./build/$${CROSS_TRIPLE} &&
             cmake --build ./build/$${CROSS_TRIPLE} &&
            ./build/$${CROSS_TRIPLE}/Tutorial 4294967296"
    volumes:
      - ./src:/app/src
      - ./build:/app/build
